apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crawler-movie
  name: crawler-movie
  namespace: crawler
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: crawler-movie
    spec:
      containers:
        - args:
            - python3
            - run.py
          env:
            - name: PGSQL_DATABASE
              value: scrape_book
            - name: PGSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: host
            - name: PGSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: password
            - name: PGSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: port
            - name: PGSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: user
          image: germey/crawler-movie
          name: crawler-movie
          resources:
            limits:
              memory: "200Mi"
              cpu: "150m"
            requests:
              memory: "200Mi"
              cpu: "150m"
      restartPolicy: Always
status: {}