version: '3'
services:
  crawler-movie:
    container_name: 'crawler-movie'
    restart: always
    build: .
    image: 'germey/crawler-movie'
    command: 'python3 run.py'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD: